@echo off
echo Removing git lock...
del /f .git\index.lock 2>nul
echo Adding files...
git add src/app/page.tsx src/app/(auth)/signup/page.tsx src/app/(auth)/reset-password/page.tsx src/app/(auth)/layout.tsx src/app/globals.css src/middleware.ts src/app/api/admin/leads/route.ts src/app/api/admin/contractors/route.ts src/components/ServiceQuizPopup.tsx src/components/auth/PasswordStrengthMeter.tsx
echo Committing...
git commit -m "security: password strength meter, security headers, hardened admin auth, logo glow"
echo Pushing...
git push
echo Done.
pause
